filter-by-commitish: true
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🛠️ Maintenance"
    label: "maintenance"
  - title: "🧪 Experimental"
    label: "experimental"
  - title: "🔧 Refine"
    label: "refine"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "maintenance"
      - "bug"
      - "experimental"
      - "refine"
  default: patch

replacers:
  - search: '/([A-Z]{2,6}-\d{1,6}-\d{1,6})/g'
    replace: "[$1](https://notion.so/sincpro/$1)"

autolabeler:
  - label: "maintenance"
    title:
      - "/^chore.+/i"
      - "/^refactor.+/i"
  - label: "bug"
    title:
      - "/^fix.+/i"
  - label: "feature"
    title:
      - "/^feat.+/i"
  - label: "experimental"
    title:
      - "/^experimental.+/i"
      - "/^preview.+/i"
  - label: "refine"
    title:
      - "/^refine.+/i"
      - "/^wip.+/i"
      - "/^fixup.+/i"
  - label: "major"
    title:
      - "/^major.+/i"

template: |
  ## What's Changed
  $CHANGES
