# yamllint configuration for GitHub workflows
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
  key-duplicates: enable
  brackets:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
