name: Check code style

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main

  workflow_call:

jobs:
  checks:
    name: Run formatting & lint checks
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/actions/prepare-env

      - name: Initialize dependencies
        run: make init

      - name: Verify code format
        run: make verify-format

      - name: Test
        run: make test
