name: Release draft

on:
  push:
    branches:
      - main
  workflow_call: {}

jobs:
  release_draft:
    name: Create / Update draft release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Author
        id: check-author
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%ae')
          if [ "$AUTHOR" = "actions@github.com" ]; then
            echo "is-bot=true" >> $GITHUB_OUTPUT
          else
            echo "is-bot=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Release Drafter
        if: steps.check-author.outputs.is-bot == 'false'
        uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_version:
    name: Update project version
    needs: release_draft
    if: needs.release_draft.result == 'success'
    uses: Sincpro-SRL/.github/.github/workflows/03.01-update-project-version.yaml@main
    secrets: inherit
