name: Update project version

on:
  workflow_run:
    workflows:
      - "Release draft"
    types:
      - completed
  workflow_call:

jobs:
  update_project_version:
    runs-on: ubuntu-latest

    if: github.event_name == 'workflow_call' || (github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Release draft' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release version
        id: get-latest-release
        uses: actions/github-script@v6
        with:
          script: |
            const allReleases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            if (allReleases.data.length === 0) {
              core.info('No previous releases found');
              core.setOutput('tag_name', '');
              return;
            }
            const latestRelease = allReleases.data[0];
            const tagName = latestRelease.tag_name;
            core.info(`Latest release tag name: ${tagName}`);
            const sanitizedTagName = tagName.replace(/[^0-9.]/g, '');
            core.info(`version to update: ${sanitizedTagName}`);
            core.setOutput('tag_name', sanitizedTagName);

      - name: Update project version
        run: |
          VERSION=${{ steps.get-latest-release.outputs.tag_name }}
          echo "Updating version to $VERSION"
          if [ -n "$VERSION" ]; then
            make update-version VERSION=$VERSION
          fi

      - name: Update main branch with the new version
        run: |
          git checkout main
          if git diff --quiet; then
            echo "No changes detected. No commit or push will be performed."
          else
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            git commit -m "chore: Update version to ${{ steps.get-latest-release.outputs.tag_name }}"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
