name: Publish release

on:
  release:
    types: [published]
    
  workflow_call:

env:
  GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
  POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}

jobs:
  publish_package:
    name: Release Process
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/actions/prepare-env

      - name: Build and Publish package
        run: |
          make publish
