name: Publish release

on:
  release:
    types: [published]

  workflow_call:
    inputs:
      environments:
        description: 'JSON array of string values to iterate (e.g., ''["pypi", "gemfury"]'' or ''["npm", "docker"]''). Each string becomes matrix.env and is passed to prepare-env as environment.'
        required: false
        type: string
        default: '["default"]'

env:
  GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
  POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}

jobs:
  publish_package:
    name: Release Process (${{ matrix.env }})
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        env: ${{ inputs.environments && fromJSON(inputs.environments) || fromJSON('["CI/CD"]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/actions/prepare-env
        with:
          environment: ${{ matrix.env }}

      - name: Initialize dependencies
        run: make init

      - name: Build and Publish package
        run: |
          make publish
